backend:
    resource: ../../src/Controller/Backend/
    type: annotation
    name_prefix: backend_
    prefix: '/EasyControl'
    options:
        expose: true

kernel:
    resource: ../../src/Kernel.php
    type: annotation
